#!/usr/bin/env node
import * as p from "@clack/prompts";
import pc from "picocolors";
import {
  execSync,
  exec as execCb,
} from "node:child_process";
import {
  existsSync,
  writeFileSync,
  mkdirSync,
  rmSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { promisify } from "node:util";

const exec = promisify(execCb);

// ─── Constants ────────────────────────────────────────────────────────────────

const FRAMEWORK_REPO = process.env["KSTACK_REPO_URL"] ?? "https://github.com/arnoxide/kstack-dev.git";
const VERSION = "0.1.0";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function isGitInstalled(): boolean {
  try { execSync("git --version", { stdio: "ignore" }); return true; }
  catch { return false; }
}

function isDockerRunning(): boolean {
  try { execSync("docker info", { stdio: "ignore" }); return true; }
  catch { return false; }
}

function detectPackageManager(): "pnpm" | "npm" | "yarn" {
  try { execSync("pnpm --version", { stdio: "ignore" }); return "pnpm"; } catch { /* */ }
  try { execSync("yarn --version", { stdio: "ignore" }); return "yarn"; } catch { /* */ }
  return "npm";
}

function toSlug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function generateEnv(answers: {
  projectName: string;
  domain: string;
  emailFrom: string;
  paystackKey: string;
  paystackPublicKey: string;
  resendKey: string;
  jwtSecret: string;
  jwtRefreshSecret: string;
  licenseKey: string;
}): string {
  const {
    projectName, domain, emailFrom,
    paystackKey, paystackPublicKey, resendKey,
    jwtSecret, jwtRefreshSecret, licenseKey,
  } = answers;

  const apiUrl = domain === "localhost"
    ? "http://localhost:3001"
    : `https://api.${domain}`;

  return [
    `# Generated by create-kstack-app v${VERSION}`,
    `# Project: ${projectName}`,
    ``,
    `# ── Database ──────────────────────────────────────────────────`,
    `DATABASE_URL=postgresql://kstack:kstack@localhost:5432/kstack`,
    ``,
    `# ── Redis ─────────────────────────────────────────────────────`,
    `REDIS_URL=redis://localhost:6379`,
    ``,
    `# ── Auth ──────────────────────────────────────────────────────`,
    `# Regenerate with: openssl rand -base64 48`,
    `JWT_SECRET=${jwtSecret}`,
    `JWT_REFRESH_SECRET=${jwtRefreshSecret}`,
    ``,
    `# ── App ───────────────────────────────────────────────────────`,
    `NODE_ENV=development`,
    `API_PORT=3001`,
    `GATEWAY_PORT=3000`,
    ``,
    `# ── URLs ──────────────────────────────────────────────────────`,
    `NEXT_PUBLIC_API_URL=${apiUrl}`,
    domain !== "localhost" ? `NEXT_PUBLIC_ROOT_DOMAIN=${domain}` : `# NEXT_PUBLIC_ROOT_DOMAIN=yourdomain.com  # uncomment in production`,
    domain !== "localhost" ? `ROOT_DOMAIN=${domain}` : `# ROOT_DOMAIN=yourdomain.com  # uncomment in production`,
    ``,
    `# ── Storage (Cloudflare R2 / S3) ──────────────────────────────`,
    `STORAGE_ENDPOINT=`,
    `STORAGE_ACCESS_KEY_ID=`,
    `STORAGE_SECRET_ACCESS_KEY=`,
    `STORAGE_BUCKET=kstack-dev`,
    `STORAGE_PUBLIC_URL=`,
    ``,
    `# ── Paystack ──────────────────────────────────────────────────`,
    `PAYSTACK_SECRET_KEY=${paystackKey}`,
    `PAYSTACK_WEBHOOK_SECRET=`,
    `NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=${paystackPublicKey}`,
    ``,
    `# ── Email (Resend) ────────────────────────────────────────────`,
    `RESEND_API_KEY=${resendKey}`,
    `EMAIL_FROM=${emailFrom || `noreply@${domain === "localhost" ? "example.com" : domain}`}`,
    ``,
    `# ── KStack License ────────────────────────────────────────────`,
    `# Community plan is free. Get a key at https://kstack.dev/pricing`,
    `KSTACK_LICENSE_KEY=${licenseKey}`,
    ``,
    `# ── Telemetry ─────────────────────────────────────────────────`,
    `# Set to false to opt out of anonymous usage telemetry`,
    `KSTACK_TELEMETRY=true`,
  ].join("\n") + "\n";
}

function randomSecret(length = 48): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  return Array.from({ length }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  // Parse args: create-kstack-app [project-name] [--source <path>] [--skip-install]
  const rawArgs = process.argv.slice(2);
  let argProjectName: string | undefined;
  let sourceOverride: string | undefined;
  let skipInstall = false;
  let skipGit = false;

  for (let i = 0; i < rawArgs.length; i++) {
    if (rawArgs[i] === "--source" && rawArgs[i + 1]) { sourceOverride = rawArgs[++i]; }
    else if (rawArgs[i] === "--skip-install") { skipInstall = true; }
    else if (rawArgs[i] === "--skip-git") { skipGit = true; }
    else if (rawArgs[i] === "--version" || rawArgs[i] === "-v") {
      console.log(`create-kstack-app v${VERSION}`);
      process.exit(0);
    } else if (rawArgs[i] === "--help" || rawArgs[i] === "-h") {
      printHelp();
      process.exit(0);
    } else if (!rawArgs[i].startsWith("--")) {
      argProjectName = rawArgs[i];
    }
  }

  // ── Banner ────────────────────────────────────────────────────────────────

  console.log();
  console.log(pc.bold(pc.white("  ██╗  ██╗███████╗████████╗ █████╗  ██████╗██╗  ██╗")));
  console.log(pc.bold(pc.white("  ██║ ██╔╝██╔════╝╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝")));
  console.log(pc.bold(pc.white("  █████╔╝ ███████╗   ██║   ███████║██║     █████╔╝ ")));
  console.log(pc.bold(pc.white("  ██╔═██╗ ╚════██║   ██║   ██╔══██║██║     ██╔═██╗ ")));
  console.log(pc.bold(pc.white("  ██║  ██╗███████║   ██║   ██║  ██║╚██████╗██║  ██╗")));
  console.log(pc.bold(pc.white("  ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝")));
  console.log();
  console.log(pc.dim(`  create-kstack-app  v${VERSION}`));
  console.log(pc.dim("  The open-source multi-tenant e-commerce framework"));
  console.log();

  p.intro(pc.bgBlue(pc.white(" Let's set up your KStack project ")));

  // ── Preflight checks ──────────────────────────────────────────────────────

  if (!skipGit && !isGitInstalled()) {
    p.log.error("Git is not installed. Install it from https://git-scm.com and try again.");
    process.exit(1);
  }

  if (!sourceOverride && !FRAMEWORK_REPO) {
    p.log.error("No repository URL configured. Use --source <path> to point to a local copy.");
    p.log.info("Example: npx create-kstack-app my-shop --source ./kstack-framework");
    process.exit(1);
  }

  const pm = detectPackageManager();

  // ── Questions ─────────────────────────────────────────────────────────────

  const answers = await p.group(
    {
      projectName: () =>
        p.text({
          message: "Project name",
          placeholder: "my-shop",
          defaultValue: argProjectName ?? "my-shop",
          initialValue: argProjectName,
          validate: (v) => {
            if (!v || v.trim().length < 2) return "Must be at least 2 characters";
            if (!/^[a-zA-Z0-9_-]+$/.test(v)) return "Only letters, numbers, hyphens, underscores";
          },
        }),

      domain: () =>
        p.text({
          message: "Your domain — stores will live at {slug}.yourdomain.com (leave blank for localhost)",
          placeholder: "yourdomain.com",
          defaultValue: "localhost",
        }),

      paystack: () =>
        p.confirm({
          message: "Set up Paystack payments now?",
          initialValue: false,
        }),

      paystackKey: ({ results }) =>
        results.paystack
          ? p.text({
              message: "Paystack secret key",
              placeholder: "sk_live_...",
              validate: (v) => {
                if (v && !v.startsWith("sk_")) return "Should start with sk_live_ or sk_test_";
              },
            })
          : Promise.resolve(""),

      paystackPublicKey: ({ results }) =>
        results.paystack
          ? p.text({
              message: "Paystack public key",
              placeholder: "pk_live_...",
              validate: (v) => {
                if (v && !v.startsWith("pk_")) return "Should start with pk_live_ or pk_test_";
              },
            })
          : Promise.resolve(""),

      email: () =>
        p.confirm({
          message: "Set up email (Resend) now?",
          initialValue: false,
        }),

      resendKey: ({ results }) =>
        results.email
          ? p.text({
              message: "Resend API key",
              placeholder: "re_...",
            })
          : Promise.resolve(""),

      emailFrom: ({ results }) =>
        results.email
          ? p.text({
              message: "From email address",
              placeholder: "noreply@yourdomain.com",
            })
          : Promise.resolve(""),

      licenseKey: () =>
        p.text({
          message: "KStack license key — leave blank for the free Community plan (https://kstack.dev/pricing)",
          placeholder: "ksk_...",
          defaultValue: "",
        }),

      gitInit: () =>
        p.confirm({
          message: "Initialise a new git repository?",
          initialValue: true,
        }),
    },
    {
      onCancel: () => {
        p.cancel("Setup cancelled.");
        process.exit(0);
      },
    },
  );

  const targetDir = resolve(process.cwd(), toSlug(answers.projectName) || "my-shop");
  const dirName = toSlug(answers.projectName) || "my-shop";

  // ── Directory check ───────────────────────────────────────────────────────

  if (existsSync(targetDir)) {
    const overwrite = await p.confirm({
      message: `Directory ${pc.yellow(dirName)} already exists. Overwrite?`,
      initialValue: false,
    });
    if (!overwrite || p.isCancel(overwrite)) {
      p.cancel("Aborted.");
      process.exit(0);
    }
    rmSync(targetDir, { recursive: true, force: true });
  }

  const spin = p.spinner();

  // ── Clone / copy framework ────────────────────────────────────────────────

  spin.start("Downloading KStack framework…");
  try {
    if (sourceOverride) {
      // Local copy for development / testing
      const src = resolve(sourceOverride);
      execSync(
        `cp -r "${src}" "${targetDir}"`,
        { stdio: "ignore" },
      );
      // Remove the local node_modules so fresh install runs cleanly
      rmSync(join(targetDir, "node_modules"), { recursive: true, force: true });
    } else {
      // Production: git clone without history
      execSync(
        `git clone --depth=1 "${FRAMEWORK_REPO}" "${targetDir}"`,
        { stdio: "ignore" },
      );
    }
    // Remove the .git folder — this will be the user's own project
    rmSync(join(targetDir, ".git"), { recursive: true, force: true });
    spin.stop("Framework downloaded.");
  } catch (err) {
    spin.stop("Download failed.");
    p.log.error(`Could not fetch the framework.\n${(err as Error).message}`);
    p.log.info("Check your internet connection or try: --source ./path/to/local/kstack");
    process.exit(1);
  }

  // ── Write .env ────────────────────────────────────────────────────────────

  spin.start("Configuring environment…");
  const envContent = generateEnv({
    projectName: answers.projectName,
    domain: (answers.domain as string) || "localhost",
    emailFrom: (answers.emailFrom as string) || "",
    paystackKey: (answers.paystackKey as string) || "",
    paystackPublicKey: (answers.paystackPublicKey as string) || "",
    resendKey: (answers.resendKey as string) || "",
    jwtSecret: randomSecret(52),
    jwtRefreshSecret: randomSecret(52),
    licenseKey: (answers.licenseKey as string) || "",
  });
  writeFileSync(join(targetDir, ".env"), envContent, "utf-8");
  spin.stop("Environment configured.");

  // ── Git init ──────────────────────────────────────────────────────────────

  if (answers.gitInit && !skipGit) {
    spin.start("Initialising git repository…");
    try {
      execSync("git init", { cwd: targetDir, stdio: "ignore" });
      execSync("git add .", { cwd: targetDir, stdio: "ignore" });
      execSync(`git commit -m "chore: initial KStack setup"`, { cwd: targetDir, stdio: "ignore" });
      spin.stop("Git repository initialised.");
    } catch {
      spin.stop("Git init skipped (git not configured).");
    }
  }

  // ── Install dependencies ──────────────────────────────────────────────────

  if (!skipInstall) {
    spin.start(`Installing dependencies with ${pm}…`);
    try {
      execSync(`${pm} install`, { cwd: targetDir, stdio: "ignore" });
      spin.stop("Dependencies installed.");
    } catch (err) {
      spin.stop("Dependency install failed.");
      p.log.warn("Run the install manually:\n  " + pc.cyan(`cd ${dirName} && ${pm} install`));
    }
  }

  // ── Database setup ────────────────────────────────────────────────────────

  const dockerRunning = isDockerRunning();
  if (dockerRunning && !skipInstall) {
    const doDb = await p.confirm({
      message: "Docker is running. Start the database and push schema now?",
      initialValue: true,
    });

    if (doDb) {
      spin.start("Starting PostgreSQL…");
      try {
        execSync("docker compose -f infra/docker-compose.yml up -d", {
          cwd: targetDir, stdio: "ignore",
        });
        // Brief pause for Postgres to be ready
        await new Promise((r) => setTimeout(r, 3000));
        spin.stop("PostgreSQL started.");

        spin.start("Pushing database schema…");
        execSync(`${pm} run db:push`, { cwd: targetDir, stdio: "ignore" });
        spin.stop("Database schema ready.");
      } catch (err) {
        spin.stop("Database setup failed.");
        p.log.warn("Run manually:\n  " + pc.cyan(`cd ${dirName} && docker compose -f infra/docker-compose.yml up -d && ${pm} db:push`));
      }
    }
  }

  // ── Done ──────────────────────────────────────────────────────────────────

  const domain = (answers.domain as string) || "localhost";
  const storefrontNote = domain === "localhost"
    ? `Storefront → ${pc.cyan("http://localhost:3003/{shop-slug}")}`
    : `Storefront → ${pc.cyan(`https://{slug}.${domain}`)}`;

  p.outro(pc.green("Your KStack project is ready!"));

  console.log();
  console.log(pc.bold("  Next steps:"));
  console.log();
  console.log(`  1  ${pc.cyan(`cd ${dirName}`)}`);

  if (!dockerRunning || skipInstall) {
    console.log(`  2  ${pc.cyan("docker compose -f infra/docker-compose.yml up -d")}   # start Postgres`);
    console.log(`  3  ${pc.cyan(`${pm} run db:push`)}   # create database tables`);
    console.log(`  4  ${pc.cyan(`${pm} run dev`)}   # start all dev servers`);
  } else {
    console.log(`  2  ${pc.cyan(`${pm} run dev`)}   # start all dev servers`);
  }

  console.log();
  console.log("  Once running:");
  console.log(`  ${pc.cyan(`${pm} run kstack store:create`)}   # create your first store`);
  console.log(`  Dashboard  →  ${pc.cyan("http://localhost:3002/login")}   (after store:create)`);
  console.log(`  API        →  ${pc.cyan("http://localhost:3001/health")}`);
  console.log(`  ${storefrontNote}`);
  console.log();
  console.log(`  Scaffold a new module:  ${pc.cyan(`${pm} run kstack module:create KStack_Blog`)}`);
  console.log();
  console.log(pc.dim("  Docs → https://kstack.dev/docs   •   License → https://kstack.dev/pricing"));
  console.log();
}

function printHelp() {
  console.log(`
${pc.bold("create-kstack-app")} v${VERSION}

${pc.bold("Usage:")}
  npx create-kstack-app [project-name] [options]

${pc.bold("Options:")}
  --source <path>    Use a local copy of the framework (for dev/testing)
  --skip-install     Skip dependency installation
  --skip-git         Skip git operations
  --version, -v      Print version
  --help, -h         Print this help

${pc.bold("Examples:")}
  npx create-kstack-app
  npx create-kstack-app my-shop
  npx create-kstack-app my-shop --source ./kstack-framework
`);
}

main().catch((err) => {
  console.error(pc.red("\nUnexpected error:"), err);
  process.exit(1);
});
