// Module: KStack_PlatformAdmin
import { boolean, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const platformAdmins = pgTable("platform_admins", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  passwordHash: text("password_hash").notNull(),
  role: text("role", { enum: ["super_admin", "admin", "viewer"] })
    .notNull()
    .default("admin"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
});

// Persists install ID and other config for each framework instance
export const frameworkConfig = pgTable("framework_config", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// One row per known framework installation — upserted on every ping
export const installPings = pgTable("install_pings", {
  installId: text("install_id").primaryKey(),
  version: text("version"),
  licenseKey: text("license_key"),
  tenantCount: integer("tenant_count").notNull().default(0),
  nodeEnv: text("node_env"),
  ip: text("ip"),
  firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
});

// License keys generated by platform admin and issued to developers
export const licenseKeys = pgTable("license_keys", {
  id: uuid("id").primaryKey().defaultRandom(),
  key: text("key").notNull().unique(),
  ownerEmail: text("owner_email").notNull(),
  ownerName: text("owner_name"),
  plan: text("plan", { enum: ["community", "pro", "enterprise"] })
    .notNull()
    .default("community"),
  isActive: boolean("is_active").notNull().default(true),
  installId: text("install_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastValidatedAt: timestamp("last_validated_at", { withTimezone: true }),
});
